---
- name: Create the default locales file (Debian)
  template: >
    src=locale.j2
    dest=/etc/default/locale
    mode=0644 owner=root group=root
  when: ansible_os_family == "Debian"
  tags:
    - common

- name: Define the system locales to generate (Debian)
  template: >
    src=locale.gen.j2
    dest=/etc/locale.gen
    mode=0644 owner=root group=root
  when: ansible_os_family == 'Debian'
  tags:
    - common

- name: Generate the default system locale (Debian)
  locale_gen: >
    name="en_US.UTF-8"
    state=present
  with_items: common_locales
  when: ansible_os_family == "Debian"
  tags:
    - common

- name: Update default locale settings (RedHat 6.x)
  lineinfile:
    dest: /etc/sysconfig/i18n
    regexp: "^LANG=.*"
    line: "LANG=\"{{ common_locales[0] }}\""
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "6"
  tags:
    - common

- name: Update default locale settings (RedHat 7.x)
  lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANG=.*"
    line: "LANG=\"{{ common_locales[0] }}\""
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"
  tags:
    - common
