---
# Defines tasks common to all nodes in the infrastructure.

- name: Gather OS specific varibles
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - common

- include: "{{ ansible_os_family }}/install.yml"
  static: no
  tags:
    - common

- include: locale.yml
- include: environment.yml
